services:
  app:
    build:
      args:
        user: mattj
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mattman-wiki-app
    container_name: mattman-wiki-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
      - ./docker-compose/app/php.ini:/usr/local/etc/php/php.ini
    networks:
      - mattman-wiki-net

  nginx:
    image: nginx:alpine
    container_name: mattman-wiki-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mattman-wiki-net

networks:
  mattman-wiki-net:
    driver: bridge
